export enum PaymentStatus {
  PENDING = 'PENDING',
  INITIALIZED = 'INITIALIZED',
  SUCCESSFUL = 'SUCCESSFUL',
  FAILED = 'FAILED',
  ABANDONED = 'ABANDONED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}
